-- ============================================================
-- post_attachments.sql
-- 게시글 여러 첨부파일 메타데이터 테이블.
--
-- 역할:
--   - 실제 파일은 Supabase Storage 버킷에 저장한다.
--   - 이 테이블은 posts.id 와 파일 URL/이름/타입/크기/Storage 경로를 연결한다.
--
-- idempotent: 여러 번 실행해도 안전.
-- 실행 위치: Supabase Dashboard → SQL Editor
-- ============================================================

alter table profiles
  add column if not exists site_role text default 'member'
    check (site_role in ('member', 'staff', 'owner')),
  add column if not exists can_manage_site boolean default false,
  add column if not exists is_admin boolean default false;

alter table posts
  add column if not exists is_hidden boolean default false;

create table if not exists post_attachments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  file_url text not null,
  file_name text not null,
  file_type text,
  file_size bigint,
  storage_path text,
  created_at timestamptz default now()
);

create index if not exists post_attachments_post_id_created_at_idx
  on post_attachments (post_id, created_at);

alter table post_attachments enable row level security;

create or replace function is_current_user_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from profiles
    where id = auth.uid()
      and (
        site_role in ('owner', 'staff')
        or can_manage_site = true
        or is_admin = true
      )
  );
$$;

drop policy if exists "post_attachments: 전체 읽기 허용" on post_attachments;
create policy "post_attachments: 전체 읽기 허용"
  on post_attachments for select
  using (
    exists (
      select 1
      from posts
      where posts.id = post_attachments.post_id
        and (posts.is_hidden = false or is_current_user_admin())
    )
  );

drop policy if exists "post_attachments: 작성자만 추가" on post_attachments;
create policy "post_attachments: 작성자만 추가"
  on post_attachments for insert
  with check (
    exists (
      select 1
      from posts
      where posts.id = post_attachments.post_id
        and posts.author_id = auth.uid()
    )
  );

drop policy if exists "post_attachments: 작성자와 관리자는 삭제" on post_attachments;
create policy "post_attachments: 작성자와 관리자는 삭제"
  on post_attachments for delete
  using (
    is_current_user_admin()
    or exists (
      select 1
      from posts
      where posts.id = post_attachments.post_id
        and posts.author_id = auth.uid()
    )
  );

select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name = 'post_attachments';
