-- ============================================================
-- production_compat_patch.sql
-- 운영 배포 코드와 Supabase 운영 DB 스키마를 맞추기 위한 보강 SQL.
--
-- 증상:
--   - 홈 통계/미리보기는 보이지만 게시판 목록이 비어 보임.
--   - 홈의 게시글 링크(/ko/post/:id)를 누르면 404가 발생함.
--
-- 원인:
--   - 배포 코드가 조회하는 최신 컬럼이 운영 DB에 아직 없으면
--     Supabase select 가 실패하고, 기존 코드는 이를 빈 목록/404로 처리할 수 있음.
--
-- 사용:
--   - Supabase SQL Editor에서 이 파일 전체를 1회 실행.
--   - idempotent: 여러 번 실행해도 안전.
-- ============================================================

alter table profiles
  add column if not exists user_code text unique,
  add column if not exists job_role text,
  add column if not exists site_role text default 'member'
    check (site_role in ('member', 'staff', 'owner')),
  add column if not exists can_manage_site boolean default false,
  add column if not exists is_admin boolean default false;

update profiles
set user_code = coalesce(user_code, public_id, 'USER-' || left(id::text, 8))
where user_code is null;

alter table posts
  add column if not exists comment_count int default 0,
  add column if not exists is_hidden boolean default false,
  add column if not exists hide_author boolean not null default false,
  add column if not exists news_subcategory text;

alter table posts
  drop constraint if exists posts_news_subcategory_check;

alter table posts
  add constraint posts_news_subcategory_check
  check (
    news_subcategory is null
    or news_subcategory in ('construction', 'manufacturing', 'shipping', 'etc')
  );

create table if not exists post_attachments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  file_url text not null,
  file_name text not null,
  file_type text,
  file_size bigint,
  storage_path text,
  created_at timestamptz default now()
);

create index if not exists post_attachments_post_id_created_at_idx
  on post_attachments (post_id, created_at);

alter table post_attachments enable row level security;

create or replace function is_current_user_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1
    from profiles
    where id = auth.uid()
      and (
        site_role in ('owner', 'staff')
        or can_manage_site = true
        or is_admin = true
      )
  );
$$;

drop policy if exists "post_attachments: 전체 읽기 허용" on post_attachments;
create policy "post_attachments: 전체 읽기 허용"
  on post_attachments for select
  using (
    exists (
      select 1
      from posts
      where posts.id = post_attachments.post_id
        and (posts.is_hidden = false or is_current_user_admin())
    )
  );

drop policy if exists "post_attachments: 작성자만 추가" on post_attachments;
create policy "post_attachments: 작성자만 추가"
  on post_attachments for insert
  with check (
    exists (
      select 1
      from posts
      where posts.id = post_attachments.post_id
        and posts.author_id = auth.uid()
    )
  );

drop policy if exists "post_attachments: 작성자와 관리자는 삭제" on post_attachments;
create policy "post_attachments: 작성자와 관리자는 삭제"
  on post_attachments for delete
  using (
    is_current_user_admin()
    or exists (
      select 1
      from posts
      where posts.id = post_attachments.post_id
        and posts.author_id = auth.uid()
    )
  );

create or replace function refresh_post_comment_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_post_id bigint;
begin
  target_post_id := coalesce(new.post_id, old.post_id);

  update posts
  set comment_count = (
    select count(*)
    from comments
    where post_id = target_post_id
  )
  where id = target_post_id;

  return coalesce(new, old);
end;
$$;

drop trigger if exists comments_refresh_post_comment_count on comments;

create trigger comments_refresh_post_comment_count
  after insert or update or delete on comments
  for each row execute function refresh_post_comment_count();

update posts
set comment_count = (
  select count(*)
  from comments
  where comments.post_id = posts.id
);

create or replace function set_post_hide_author()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.hide_author := coalesce(
    (select is_admin from profiles where id = new.author_id),
    false
  );
  return new;
end;
$$;

drop trigger if exists trg_set_post_hide_author on posts;

create trigger trg_set_post_hide_author
  before insert on posts
  for each row execute function set_post_hide_author();

create or replace function increment_view_count(post_id_input bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update posts
  set view_count = coalesce(view_count, 0) + 1
  where id = post_id_input;
end;
$$;

select 'production compatibility patch applied' as result;
