-- ============================================================
-- 산업안전보건 통합 커뮤니티 포털 스키마
-- ============================================================

-- profiles
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  nickname text not null,
  nationality text,
  age int,
  user_role text check (user_role in ('근로자', '관리자')) not null,
  industry text check (industry in ('건설업', '제조업', '기타')) not null,
  manager_type text check (
    manager_type in (
      '안전관리자', '보건관리자', '현장소장',
      '관리감독자', '안전보건총괄책임자', '안전보건관리책임자'
    )
  ),
  profile_image text,
  created_at timestamptz default now()
);

-- categories
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  sort_order int default 0
);

insert into categories (name, slug, sort_order) values
  ('공지사항', 'notice', 1),
  ('자유게시판', 'free', 2),
  ('안전보건 자료실', 'resources', 3),
  ('법령/규정', 'law', 4),
  ('산업안전 뉴스', 'news', 5),
  ('사고사례 공유', 'accident', 6),
  ('교육자료', 'education', 7),
  ('안전점검 체크리스트', 'checklist', 8),
  ('현장사진', 'photos', 9),
  ('Q&A', 'qna', 10)
on conflict (slug) do nothing;

-- posts
create table if not exists posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category_slug text not null references categories(slug),
  author_id uuid references profiles(id) on delete set null,
  image_url text,
  file_url text,
  view_count int default 0,
  like_count int default 0,
  qna_status text default '답변대기' check (qna_status in ('답변대기', '답변완료')),
  accident_type text,
  accident_cause text,
  prevention_plan text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- comments
create table if not exists comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  author_id uuid references profiles(id) on delete set null,
  content text not null,
  parent_comment_id bigint references comments(id) on delete cascade,
  created_at timestamptz default now()
);

-- likes
create table if not exists likes (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  user_id uuid not null references profiles(id) on delete cascade,
  created_at timestamptz default now(),
  unique (post_id, user_id)
);

-- reports
create table if not exists reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  reporter_id uuid references profiles(id) on delete set null,
  reason text,
  status text default '접수' check (status in ('접수', '처리중', '처리완료')),
  created_at timestamptz default now()
);

-- ============================================================
-- RLS 활성화
-- ============================================================

alter table profiles enable row level security;
alter table posts enable row level security;
alter table comments enable row level security;
alter table likes enable row level security;
alter table reports enable row level security;

-- ============================================================
-- profiles RLS
-- ============================================================

create policy "profiles: 전체 읽기 허용"
  on profiles for select using (true);

create policy "profiles: 본인만 insert"
  on profiles for insert with check (auth.uid() = id);

create policy "profiles: 본인만 update"
  on profiles for update using (auth.uid() = id);

-- ============================================================
-- posts RLS
-- ============================================================

create policy "posts: 전체 읽기 허용"
  on posts for select using (true);

create policy "posts: 로그인 사용자만 작성"
  on posts for insert with check (auth.uid() = author_id);

create policy "posts: 본인만 수정"
  on posts for update using (auth.uid() = author_id);

create policy "posts: 본인만 삭제"
  on posts for delete using (auth.uid() = author_id);

-- ============================================================
-- comments RLS
-- ============================================================

create policy "comments: 전체 읽기 허용"
  on comments for select using (true);

create policy "comments: 로그인 사용자만 작성"
  on comments for insert with check (auth.uid() = author_id);

create policy "comments: 본인만 삭제"
  on comments for delete using (auth.uid() = author_id);

-- ============================================================
-- likes RLS
-- ============================================================

create policy "likes: 전체 읽기 허용"
  on likes for select using (true);

create policy "likes: 본인만 추가"
  on likes for insert with check (auth.uid() = user_id);

create policy "likes: 본인만 삭제"
  on likes for delete using (auth.uid() = user_id);

-- ============================================================
-- reports RLS
-- ============================================================

create policy "reports: 로그인 사용자만 신고"
  on reports for insert with check (auth.uid() = reporter_id);

-- ============================================================
-- updated_at 자동 갱신 트리거
-- ============================================================

create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace trigger posts_updated_at
  before update on posts
  for each row execute function update_updated_at();

-- ============================================================
-- 조회수 증가 RPC
-- ============================================================

create or replace function increment_view_count(post_id_input bigint)
returns void as $$
begin
  update posts
  set view_count = view_count + 1
  where id = post_id_input;
end;
$$ language plpgsql security definer;

-- ============================================================
-- 회원가입 시 profiles 자동 생성 트리거 (선택사항)
-- signup 페이지에서 직접 insert하므로 필수는 아님
-- ============================================================
