-- Existing Supabase project upgrade script.
-- Run this in Supabase SQL Editor after backing up production data.

alter table profiles
  add column if not exists public_id text unique,
  add column if not exists account_status text default 'active'
    check (account_status in ('active', 'suspended', 'banned')),
  add column if not exists report_count int default 0,
  add column if not exists suspended_until timestamptz,
  add column if not exists is_admin boolean default false;

update profiles
set public_id = 'USER-' || left(id::text, 8)
where public_id is null;

update profiles
set is_admin = true
where user_role = '관리자'
  and is_admin = false;

alter table posts
  add column if not exists is_hidden boolean default false,
  add column if not exists hidden_reason text;

alter table comments
  add column if not exists is_hidden boolean default false,
  add column if not exists hidden_reason text;

create table if not exists answers (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  author_id uuid references profiles(id) on delete set null,
  content text not null,
  source text,
  is_selected boolean default false,
  is_admin_answer boolean default false,
  is_hidden boolean default false,
  hidden_reason text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists answer_opinions (
  id bigint generated by default as identity primary key,
  answer_id bigint not null references answers(id) on delete cascade,
  author_id uuid references profiles(id) on delete set null,
  opinion_type text check (
    opinion_type in ('이의제기', '추가의견', '근거보완', '오류수정요청')
  ) not null,
  content text not null,
  source text,
  is_hidden boolean default false,
  hidden_reason text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table answers
  add column if not exists is_hidden boolean default false,
  add column if not exists hidden_reason text;

alter table answer_opinions
  add column if not exists is_hidden boolean default false,
  add column if not exists hidden_reason text;

-- Upgrade the old post-only reports table to a generic report table.
create table if not exists reports (
  id bigint generated by default as identity primary key,
  target_type text,
  target_id bigint,
  reported_user_id uuid references profiles(id) on delete cascade,
  reporter_id uuid references profiles(id) on delete cascade,
  reason text,
  detail text,
  status text default '접수',
  created_at timestamptz default now()
);

alter table reports
  add column if not exists target_type text,
  add column if not exists target_id bigint,
  add column if not exists reported_user_id uuid references profiles(id) on delete cascade,
  add column if not exists detail text;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_name = 'reports'
      and column_name = 'post_id'
  ) then
    alter table reports alter column post_id drop not null;
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_name = 'reports'
      and column_name = 'post_id'
  ) then
    execute $sql$
      update reports r
      set target_type = 'post',
          target_id = post_id,
          reported_user_id = p.author_id
      from posts p
      where r.post_id = p.id
        and r.target_type is null
        and r.target_id is null
    $sql$;
  end if;
end $$;

update reports
set reason = '기타'
where reason is null;

alter table reports
  alter column target_type set not null,
  alter column target_id set not null,
  alter column reason set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'reports_target_type_check'
  ) then
    alter table reports
      add constraint reports_target_type_check
      check (target_type in ('post', 'comment', 'answer', 'answer_opinion'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'reports_reason_check'
  ) then
    alter table reports
      add constraint reports_reason_check
      check (
        reason in (
          '욕설/비방',
          '성희롱',
          '혐오/차별',
          '허위사실',
          '개인정보 노출',
          '회사명/현장명 언급',
          '스팸/광고',
          '기타'
        )
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'reports_status_check'
  ) then
    alter table reports
      add constraint reports_status_check
      check (status in ('접수', '검토중', '처리완료', '반려'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'reports_target_reporter_unique'
  ) then
    alter table reports
      add constraint reports_target_reporter_unique
      unique(target_type, target_id, reporter_id);
  end if;
end $$;

alter table answers enable row level security;
alter table answer_opinions enable row level security;
alter table reports enable row level security;

create or replace function is_current_user_admin()
returns boolean as $$
  select exists (
    select 1
    from profiles
    where id = auth.uid()
      and (is_admin = true or user_role = '관리자')
  );
$$ language sql security definer stable;

create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace trigger answers_updated_at
  before update on answers
  for each row execute function update_updated_at();

create or replace trigger answer_opinions_updated_at
  before update on answer_opinions
  for each row execute function update_updated_at();

create or replace function update_report_count_and_suspend()
returns trigger as $$
declare
  total_reports int;
begin
  select count(*)
  into total_reports
  from reports
  where reported_user_id = new.reported_user_id
    and status in ('접수', '검토중', '처리완료');

  update profiles
  set report_count = total_reports
  where id = new.reported_user_id;

  if total_reports >= 5 then
    update profiles
    set account_status = 'suspended',
        suspended_until = now() + interval '7 days'
    where id = new.reported_user_id
      and account_status <> 'banned';
  end if;

  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists trigger_update_report_count_and_suspend on reports;

create trigger trigger_update_report_count_and_suspend
  after insert on reports
  for each row execute function update_report_count_and_suspend();

drop policy if exists "profiles: 관리자는 제재 정보 update" on profiles;
create policy "profiles: 관리자는 제재 정보 update"
  on profiles for update using (is_current_user_admin());

drop policy if exists "posts: 전체 읽기 허용" on posts;
create policy "posts: 전체 읽기 허용"
  on posts for select using (is_hidden = false or is_current_user_admin());

drop policy if exists "posts: 관리자는 수정" on posts;
create policy "posts: 관리자는 수정"
  on posts for update using (is_current_user_admin());

drop policy if exists "posts: 관리자는 삭제" on posts;
create policy "posts: 관리자는 삭제"
  on posts for delete using (is_current_user_admin());

drop policy if exists "comments: 전체 읽기 허용" on comments;
create policy "comments: 전체 읽기 허용"
  on comments for select using (is_hidden = false or is_current_user_admin());

drop policy if exists "comments: 관리자는 수정" on comments;
create policy "comments: 관리자는 수정"
  on comments for update using (is_current_user_admin());

drop policy if exists "comments: 관리자는 삭제" on comments;
create policy "comments: 관리자는 삭제"
  on comments for delete using (is_current_user_admin());

drop policy if exists "answers: 전체 읽기 허용" on answers;
create policy "answers: 전체 읽기 허용"
  on answers for select using (is_hidden = false or is_current_user_admin());

drop policy if exists "answers: 로그인 사용자만 작성" on answers;
create policy "answers: 로그인 사용자만 작성"
  on answers for insert with check (auth.uid() = author_id);

drop policy if exists "answers: 본인만 수정" on answers;
create policy "answers: 본인만 수정"
  on answers for update using (auth.uid() = author_id);

drop policy if exists "answers: 관리자는 수정" on answers;
create policy "answers: 관리자는 수정"
  on answers for update using (is_current_user_admin());

drop policy if exists "answers: 본인만 삭제" on answers;
create policy "answers: 본인만 삭제"
  on answers for delete using (auth.uid() = author_id);

drop policy if exists "answers: 관리자는 삭제" on answers;
create policy "answers: 관리자는 삭제"
  on answers for delete using (is_current_user_admin());

drop policy if exists "answer_opinions: 전체 읽기 허용" on answer_opinions;
create policy "answer_opinions: 전체 읽기 허용"
  on answer_opinions for select using (is_hidden = false or is_current_user_admin());

drop policy if exists "answer_opinions: 로그인 사용자만 작성" on answer_opinions;
create policy "answer_opinions: 로그인 사용자만 작성"
  on answer_opinions for insert with check (auth.uid() = author_id);

drop policy if exists "answer_opinions: 본인만 수정" on answer_opinions;
create policy "answer_opinions: 본인만 수정"
  on answer_opinions for update using (auth.uid() = author_id);

drop policy if exists "answer_opinions: 관리자는 수정" on answer_opinions;
create policy "answer_opinions: 관리자는 수정"
  on answer_opinions for update using (is_current_user_admin());

drop policy if exists "answer_opinions: 본인만 삭제" on answer_opinions;
create policy "answer_opinions: 본인만 삭제"
  on answer_opinions for delete using (auth.uid() = author_id);

drop policy if exists "answer_opinions: 관리자는 삭제" on answer_opinions;
create policy "answer_opinions: 관리자는 삭제"
  on answer_opinions for delete using (is_current_user_admin());

drop policy if exists "reports: 본인 신고 내역과 관리자 읽기" on reports;
create policy "reports: 본인 신고 내역과 관리자 읽기"
  on reports for select using (
    reporter_id = auth.uid()
    or reported_user_id = auth.uid()
    or is_current_user_admin()
  );

drop policy if exists "reports: 로그인 사용자만 신고" on reports;
create policy "reports: 로그인 사용자만 신고"
  on reports for insert with check (auth.uid() = reporter_id);

drop policy if exists "reports: 관리자는 상태 수정" on reports;
create policy "reports: 관리자는 상태 수정"
  on reports for update using (is_current_user_admin());
